baseURL = "https://doctorflow.net/"
languageCode = "pt-PT"
title = "Dr. Flow"

theme = "flow"
canonifyURLs = true

copyright = "Copyright (c) 2019, 2020 Ricardo Anselmo de Castro"

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[frontmatter]
  date = [":fileModTime", ":default"]
  lastmod = [":fileModTime", ":default"]
  publishDate = [":fileModTime", ":default"]

[params]
  title = "Dr. Flow"

# [social]
#   twitter = "racastro"
